-- Generated by apply.py from the wallpaper. Edit theme/templates/colors.lua, not this file.
return {
    scheme          = "@scheme@",
    primary         = "@primary_hex@",
    secondary       = "@secondary_hex@",
    -- Hyprland: the border of the windows without focus and the shadow (ARGB)
    inactive_border = "@overlay_hex@",
    shadow          = "@shadow_hex@",
}
