# Alle Platten, alle Attribute, woechentlicher Kurztest So 02:00, Langtest Sa 03:00 monatlich
DEVICESCAN -a -o on -S on -n standby,q -s (S/../.././02|L/../01/./03) -m root -M exec /usr/local/bin/smartd-notify
